# Generated by Django 2.1 on 2018-08-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('size', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
