# Generated by Django 2.0.6 on 2018-06-09 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('28871a24-8bf7-48a5-bf50-7a9a0d034af8'), primary_key=True, serialize=False),
        ),
    ]
