# Generated by Django 2.0.6 on 2018-06-20 15:38

from django.db import migrations


def migrate_tasks(apps, schema_editor):
    Task = apps.get_model('myapp', 'Task')

    task1 = Task.objects.create(text='hi', checked=True)
    task2 = Task.objects.create(text='HI', checked=False)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180609_0832'),
    ]

    operations = [
        migrations.RunPython(migrate_tasks, migrations.RunPython.noop)
    ]
