# Generated by Django 2.0.7 on 2018-07-06 14:16

from django.db import migrations


def add_articles(apps, schema_editor):
    Article = apps.get_model('article_app', 'Article')
    Category = apps.get_model('article_app', 'Category')
    User = apps.get_model('auth', 'User')

    user1 = User.objects.get(username='varya')
    user2 = User.objects.get(username='nana')

    art1 = Article(title='My world',
                   content='Return the context variable name that will be used to contain the list of data that this '
                           'view is manipulating. If object_list is a queryset of Django objects and context '
                           'object_name is not set, the context name will be the model_name of the model that '
                           'the queryset is composed from, with postfix appended. For example, the model Article '
                           'would have a context object named article_list.',
                   category=Category.objects.get(name='World'),
                   status=True,
                   user=user1)
    art1.save()

    art2 = Article(title='Your world',
                   content='Return a boolean specifying whether to display the page if no objects are available.'
                           ' If this method returns False and no objects are available, the view will raise a 404'
                           ' instead of displaying an empty page. By default, this is True.',
                   category=Category.objects.get(name='World'),
                   status=True,
                   user=user1)
    art2.save()

    art3 = Article(title='RobotoCake',
                   content='Cake is a form of sweet dessert that is typically baked. In its oldest forms, cakes'
                           ' were modifications of breads, but cakes now cover a wide range of preparations that'
                           ' can be simple or elaborate, and that share features with other desserts such as pastries,'
                           ' meringues, custards, and pies.',
                   category=Category.objects.get(name='Design'),
                   user=user2)
    art3.save()

    art4 = Article(title='Echo cake',
                   content='Cake is often served as a celebratory dish on ceremonial occasions, such as weddings,'
                           ' anniversaries, and birthdays. There are countless cake recipes; some are bread-like,'
                           ' some are rich and elaborate, and many are centuries old. Cake making is no longer'
                           ' a complicated procedure; while at one time considerable labor went into cake making'
                           ' (particularly the whisking of egg foams), baking equipment and directions have been'
                           ' simplified so that even the most amateur cook may bake a cake.',
                   category=Category.objects.get(name='Design'),
                   user=user1)
    art4.save()

    art5 = Article(title='What is technology?',
                   content='Technology ("science of craft", from Greek τέχνη, techne, "art, skill, cunning of hand";'
                           ' and -λογία, -logia[2]) is first robustly defined by Jacob Bigelow in 1829 as: '
                           '"...principles, processes, and nomenclatures of the more conspicuous arts, particularly'
                           ' those which involve applications of science, and which may be considered useful, by'
                           ' promoting the benefit of society, together with the emolument [compensation [3]] of'
                           ' those who pursue them" [4].',
                   category=Category.objects.get(name='Technology'),
                   status=True,
                   user=user1)
    art5.save()


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_article_category'),
    ]

    operations = [
        migrations.RunPython(add_articles),
    ]
