# Generated by Django 2.0.7 on 2018-07-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0005_auto_20180706_2151'),
    ]

    operations = [
    ]
