# Generated by Django 2.0.7 on 2018-07-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0007_auto_20180719_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
