# Generated by Django 2.0.6 on 2018-06-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('actors', models.ManyToManyField(blank=True, null=True, to='movienews_app.ActorModel')),
                ('directors', models.ManyToManyField(blank=True, null=True, to='movienews_app.DirectorModel')),
                ('genres', models.ManyToManyField(blank=True, null=True, to='movienews_app.GenreModel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movienews_app.MovieModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
                ('genres', models.ManyToManyField(to='movienews_app.GenreModel')),
            ],
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movienews_app.UserModel'),
        ),
        migrations.AddField(
            model_name='genremodel',
            name='users',
            field=models.ManyToManyField(to='movienews_app.UserModel'),
        ),
        migrations.AddField(
            model_name='directormodel',
            name='movies',
            field=models.ManyToManyField(to='movienews_app.MovieModel'),
        ),
        migrations.AddField(
            model_name='actormodel',
            name='movies',
            field=models.ManyToManyField(to='movienews_app.MovieModel'),
        ),
    ]
