# Generated by Django 2.0.6 on 2018-06-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienews_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
