# Generated by Django 2.0.6 on 2018-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienews_app', '0003_remove_moviemodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
