# Generated by Django 2.0.6 on 2018-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienews_app', '0004_moviemodel_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genremodel',
            name='summary',
        ),
        migrations.AlterField(
            model_name='genremodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='actors',
            field=models.ManyToManyField(to='movienews_app.ActorModel'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='directors',
            field=models.ManyToManyField(to='movienews_app.DirectorModel'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='genres',
            field=models.ManyToManyField(to='movienews_app.GenreModel'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
