# Generated by Django 2.0.6 on 2018-06-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienews_app', '0005_auto_20180626_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actormodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='actormodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='actormodel',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='directormodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='directormodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='directormodel',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='actormodel',
            name='gender',
            field=models.CharField(default='No data.', max_length=16),
        ),
        migrations.AddField(
            model_name='actormodel',
            name='name',
            field=models.CharField(default='No data.', max_length=64),
        ),
        migrations.AddField(
            model_name='directormodel',
            name='gender',
            field=models.CharField(default='No data.', max_length=16),
        ),
        migrations.AddField(
            model_name='directormodel',
            name='name',
            field=models.CharField(default='No data.', max_length=64),
        ),
        migrations.AlterField(
            model_name='actormodel',
            name='bio',
            field=models.TextField(default='No data.'),
        ),
        migrations.AlterField(
            model_name='actormodel',
            name='image',
            field=models.CharField(default='No data.', max_length=256),
        ),
        migrations.AlterField(
            model_name='directormodel',
            name='bio',
            field=models.TextField(default='No data.'),
        ),
        migrations.AlterField(
            model_name='directormodel',
            name='image',
            field=models.CharField(default='No data.', max_length=256),
        ),
    ]
