# Generated by Django 2.0.6 on 2018-06-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movienews_app', '0006_auto_20180626_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actormodel',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='directormodel',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='genremodel',
            name='users',
        ),
    ]
