# Generated by Django 2.0.6 on 2018-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienews_app', '0007_auto_20180626_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actormodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='directormodel',
            name='gender',
        ),
        migrations.AddField(
            model_name='actormodel',
            name='birthday',
            field=models.CharField(default='No data.', max_length=32),
        ),
        migrations.AddField(
            model_name='actormodel',
            name='deathday',
            field=models.CharField(default='No data.', max_length=32),
        ),
        migrations.AddField(
            model_name='directormodel',
            name='birthday',
            field=models.CharField(default='No data.', max_length=32),
        ),
        migrations.AddField(
            model_name='directormodel',
            name='deathday',
            field=models.CharField(default='No data.', max_length=32),
        ),
    ]
