# Generated by Django 2.0.6 on 2018-06-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movienews_app', '0009_auto_20180626_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
