# Generated by Django 2.0.6 on 2018-06-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienews_app', '0011_auto_20180626_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bio',
            field=models.CharField(max_length=128),
        ),
    ]
