# Generated by Django 2.0.6 on 2018-06-20 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_url', models.CharField(max_length=250)),
                ('short_url', models.CharField(max_length=100)),
                ('click_count', models.IntegerField(default=0)),
            ],
        ),
    ]
